#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'locale', git: 'https://github.com/deepak/chef-locale', ref: '2669bd937f589b6ad542da4eb1baa42cfe251030'
cookbook 'apt'
cookbook 'build-essential'
cookbook 'cmake', git: 'https://github.com/phlipper/chef-cmake'
cookbook 'libqt4', git: 'https://github.com/phlipper/chef-libqt4'

cookbook 'postgresql', git: 'https://github.com/phlipper/chef-postgresql'

cookbook 'ulimit', git: 'https://github.com/bmhatfield/chef-ulimit'

cookbook 'rvm', git: 'https://github.com/fnichol/chef-rvm'


