source 'https://rubygems.org'

#ruby=2.1.0
#ruby-gemset=brewbit-backup

# Provides an elegant DSL in Ruby for performing backups on UNIX-like systems.
gem 'backup', '4.0.1'

# Loads environment variables from `.env`. https://github.com/bkeepers/dotenv
gem 'dotenv'
